blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name = 'all_blogs'),
    #int will capture any intergers and send it to the views.blog method
    #with the int value be accessed in blog_id variable
    path('<int:blog_id>', views.blog, name = 'detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('blog/', include('blog.urls'), name='blog'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    #blogs have title, date and text / html
        title = models.CharField(
            max_length = 40
        )

        date = models.DateField()

        blogContent = models.TextField()

        #returns the default name the class instance
        #required to see the name in the admin browser
        def __str__(self):
            return self.title

portfolio/models.py
from django.db import models

# Create your models here.
#uses inheritance in the brackets
class PortfolioProject(models.Model):
    title = models.CharField(
        max_length = 40
    )

    description = models.CharField(
        max_length = 400
    )

    project_image = models.ImageField(
        #LOCATION TO UPLOAD THE IMAGES TOO
        upload_to='portfolio/images/'
    )

    project_url = models.URLField(blank=True)

    #returns the default name the class instance
    #required to see the name in the admin browser
    def __str__(self):
        return self.title

tech/models.py
from django.db import models

# Create your models here.
class Technologies(models.Model):
    title = models.CharField(
        max_length = 30
        )

    tech_image = models.ImageField(
        #LOCATION TO UPLOAD THE IMAGES TOO
        upload_to='tech/images/'
    )

    #returns the default name the class instance
    #required to see the name in the admin browser
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(request):

        #grabs all the objects from the database
    blogs = Blog.objects.all()
    num = len(blogs)
    #blogs = Blog.objects.order_by('-date')[:5]
    return render(request, 'blog/all_blogs.html', {'blogs': blogs, 'count':num})

def blog(request, blog_id):
    #get the data object making the id of blog_id
    #blog = Blog.objects.get(id=blog_id)
    #this is better as it returns a 404 if there is now mantching blog # IDEA:
    #pk standing for primary key, so the primary key for this get is equal to blog_id
    blog = get_object_or_404(Blog, pk=blog_id)
    return render (request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import PortfolioProject
from tech.models import Technologies

# Create your views here.
def home (request):

    #grab project objects from the database
    #grabs all the objects from the database
    projects = PortfolioProject.objects.all()
    technologies = Technologies.objects.all()
    print(projects)
    return render(request, 'portfolio/home.html', {'projects' : projects, 'technologies' : technologies})

tech/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>This is a Blog Page</h1>
<h3>Andrew has written {{ blogs.count }} blog{{ blogs.count | pluralize }}</h3>


{% for blog in blogs %}
<a href = "{% url 'blog:detail' blog.id %}"><h2>{{blog.title}}</h2></a>
<h3>{{blog.date|date:'M d Y'}}</h3>
<p>{{blog.blogContent|truncatewords:50}}</p>
<br>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1> Blog Detail </h1>

<h2>{{ blog.title }}</h2>
<br>
<h5>{{ blog.date }}</h5>
<br>
<p> {{ blog.blogContent}} </p>

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>

{% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

    <!-- Font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">




  </head>
  <body>
        {% load static %}
        <nav class="navbar navbar-expand-xl navbar-light fixed-top shadow-lg pb-3 pt-2 bg-white">
          <!-- <a class="navbar-brand" href="#">
              <img src="{% static 'portfolio/rocket.png' %}" class="d-inline-block align-top mr-1 img-fluid" width="35" height = "35">
              Andrew White</a> -->

           <img src="{% static 'portfolio/rocket.png' %}" class="d-inline-block align-top mr-3 img-fluid" width="35" height = "35">

           <h3 class="my-auto justify-content-end">Andrew White</h3>


         <!-- toggler/collapsible button      -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end lead" id="navbarSupportedContent">
            <ul class="navbar-nav mr-2">
              <li class="nav-item active mx-1">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <div class="dropdown-divider"></div>
              <li class="nav-item active mx-1">
                <a class="nav-link" href="{% url 'home'%}#portfolio">Portfolio <span class="sr-only">(current)</span></a>
              </li>
              <div class="dropdown-divider"></div>
              <li class="nav-item mx-1">
                 <a class="nav-link" href="{% url 'home'%}#aboutMe">About Me</a>
               </li>
               <div class="dropdown-divider"></div>
               <li class="nav-item mx-1">
                 <a class="nav-link" href="{% url 'home'%}#tech">Technologies</a>
               </li>
              <div class="dropdown-divider"></div>
              <li class="nav-item mx-1">
                <a class="nav-link" href="{% static 'portfolio/resume.pdf' %}">Resume</a>
              </li>
              <div class="dropdown-divider"></div>
              <li class="nav-item mx-1">
                <a class="nav-link" href="https://www.linkedin.com/in/andrew-white-15a03941/">LinkedIn  <i class="fab fa-linkedin fa-lg"></i> </a>
              </li>
              <div class="dropdown-divider"></div>
              <li class="nav-item mx-1">
                <a class="nav-link" href="https://github.com/arlw87">Github <i class="fab fa-github fa-lg"></i></a>
              </li>
              <div class="dropdown-divider"></div>
             <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'home'%}#contactMe">Contact  <i class="far fa-envelope fa-lg"></i></a>
              </li>
            </ul>
          </div>
        </nav>



     {% block content %}{% endblock %}








    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script>
    $('.navbar-nav>li>a').on('click', function(){
            $('.navbar-collapse').collapse('hide');
        });
    </script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<div class="jumbotron jumbotron-fluid mb-n3 ">
    <div class="container">

        <!-- <div class="container"> -->
            <!-- justify-content-md-center -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-12">
                        <img src="{% static 'portfolio/blackAndWhite2.png' %}" id="MeImage" class="img-fluid mx-auto d-block">
                </div>
                <div class="col-1">
                </div>
                <div class="col-lg-7 col-md-7 col-12 my-auto">
                    <div class="auto-my">
                        <h1 class="display-3 text-md-left text-center headlineText text-white">Software Developer</h1>
                        <br>
                        <h3 class="text-white text-justify" id="headlineDesc" >
                            Hello, I'm a self taught and highly motivated developer that is passionate about using technology to create innovative solutions to todays problems </h3>
                        <br>
                    </div>
                </div>
            </div>

        <!-- </div> -->
    </div>
</div>

<div class="col-12" id="portfolio">
    <div class="container col-12 col-xl-10 pb-3 mx-auto pt-3" id="portfolio">
        <h1 class="text-center display-4 headlineText">Portfolio</h1>
        <hr>
        <div class="row row-cols-md-2 row-cols-lg-3">

        {% for project in projects %}
        <div class="mb-3 card-deck mx-auto">
            <div class="card mb-1 shadow" >
              <img class="card-img-top" src="{{ project.project_image.url }}" alt="Card image">
              <div class="card-body d-flex flex-column align-items-start" >
                <h4 class="card-title ">{{ project.title }}</h4>
                {% with max_chars=240%}
                    <p class="card-text pb-5 text-justify">
                        {{ project.description |truncatechars:max_chars}}
                    </p>
                {% endwith %}
                {% if project.project_url %}
                <a href="{{project.project_url}}" class="btn btn-primary mt-auto">
                    Find out more
                </a>
                {% endif %}
              </div>
            </div>
        </div>
        {% endfor %}

        </div>
    </div>
<!-- </div> -->
</div>

<div class="container col-12 pt-3 pb-5" id="aboutMe">
    <div class = "col-12 col-xl-10 mx-auto">
        <h1 class="display-4 text-center headlineText">About Me</h1>
        <hr>
        <p class="lead text-justify">I am a degree qualified Electronic Engineer based near Southampton, UK who is developing software programming skills with the ambition of changing career. </p>

        <p class="lead text-justify">Having graduated at Southampton University, I have spent 10 years in the Space industry first as a Systems engineer working on Telecommunication satellites, now as a Senior engineer working in the SatCom sector repairing ground station communication amplifiers.</p>

        <p class="lead text-justify">Having enjoyed doing some programming in my professional roles, using Python and VBA, I started to do some self learning and small projects in my spare time. In the last 18 months I have been spending a lot of my free time coding, using <a href="https:www.udemy.com" class=hyperLinkColor> Udemy </a> courses, books and online resources to learn a variety of different <a href="{% url 'home'%}#tech" class="hyperLinkColor">languages</a> and <a href="{% url 'home'%}#tech" class=hyperLinkColor>frameworks</a>. I have used this growing knowledge to create a variety of exciting and substantial <a href ="{% url 'home'%}#portfolio" class="hyperLinkColor">projects</a> using software and hardware. </p>

        <p class="lead text-justify">Since the beginning of 2020 I went part time to further accelerate my learning. I have a real passion for using technologies to solve problems and improve peoples lives and a real drive to continue to grow and develop my skills. I am actively looking to start my professional career in software development, so if you would like to find out more please <a href= "{% url 'home'%}#contactMe" class="hyperLinkColor">contact</a> me.
        </p>
    </div>
</div>

<div class="container col-12 pt-3 pb-5" id="tech">
    <div class = "col-12 col-xl-10 mx-auto ">
        <h1 class="display-4 text-center headlineText">Technologies</h1>
        <hr>
            <div class="row pt-3">
                {% for tech in technologies %}
                <div class="col-6 col-md-4 col-lg-2 mx-auto py-3">
                    <img src="{{ tech.tech_image.url }}" class="mx-auto d-block" height="100" width="100">
                    <h5 class="pt-3 text-center">{{ tech.title }}</h5>
                </div>
                {% endfor %}
            </div>
    </div>
</div>

<div class="container col-12 pt-3 pb-4" id="contactMe">
    <div class = "col-12 col-xl-10 mx-auto">
        <h1 class="display-4 text-center headlineText">Contact Me</h1>
        <hr>
        <h3 class="text-center hyperLinkColor">arlw87@googlemail.com<h3>
    </div>
</div>

<!-- <footer class="footer"> -->
    <div class="bg-dark text-white py-2">
        <p class="my-auto col-12 text-center">Github and LinkedIn icons from <a href="https://fontawesome.com/" class="hyperLinkColor" >font awesome</a> Technology icons from <a href="https://iconscout.com/contributors/icon-mafia" class="hyperLinkColor">Icon Mafia</a>, <a href="https://www.flaticon.com/authors/pixel-perfect" class="hyperLinkColor" >Pixel Perfect</a> and <a href="https://iconscout.com/contributors/vorillaz/icons" class="hyperLinkColor">Vorillaz</a> Rocket from <a href="https://www.flaticon.com/authors/pixel-perfect" class="hyperLinkColor"> Pixel Perfect</p>
    </div>
<!-- </footer> -->
{% endblock %}